---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codezilla-deployment
  namespace: codezilla
  labels:
    app: codezilla
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codezilla
  template:
    metadata:
      labels:
        app: codezilla
    spec:
      containers:
      - name: codezilla
        image: ghcr.io/tank-bohr/codezilla@sha256:bb52ba64b37bf02b05c9ebe5430ee4071b4396b230b015d07571a7f0c74a94ec
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
